### ISSUE TITLE
Cannot use moogle when moogled

### ISSUE THREAD

**Issue by Lictor000** [xenophile127/FFA-Disassembly#19]
Hi, I hope this is the right place to report this.
I've been playing your Legend of the Mana Sword rom hack (version 2024-3-29, Amanda patch), and unless I'm not understanding your fix, it appears that I am not able to use the Moogle item while moogled. I have been able to reproduce it at least three times so far: got moogled, I equipped the moogle item but was unable to use it and had to wait for the end of the debuff. It didn't work even if the moogle item was already equipped.

Anyway thanks a lot for your work. I'm discovering just now this game and decided to give it a try using your hack.

**Comment by xenophile127** [comment]
Confirmed. Heal works but the Moogle item does not. I have not tested the Unicorn item but it likely has the same issue.

Thank you for the report! I'll try to get this fixed for the next release.

**Comment by xenophile127** [comment]
@Lictor000, fixed in commit c4a4fbf. Nice find and thank you for the report.
